import type { AgentProfileBundle } from "../src/index.ts";

export function buildSyntheticAgentProfile(
  projectId = "synthetic-project",
): AgentProfileBundle {
  return {
    schemaVersion: 1,
    projectId,
    trust: "USER_CONFIGURED",
    agent: {
      id: "review-agent",
      name: "Synthetic Review Agent",
      description: "Reviews fictional changes without executing tools.",
      version: "1.2.0",
      instructionSourceIds: ["project-review-rules"],
      skillIds: ["dependency-review", "test-review"],
      preferredModels: ["model-balanced", "model-small"],
      allowedModels: ["model-balanced", "model-small"],
      allowedTools: ["read_file", "run_tests"],
      forbiddenTools: ["deploy", "write_file"],
      context: {
        include: ["git_diff", "test_state"],
        exclude: ["unrelated_history"],
        continuityBudgetBytes: 16_384,
        instructionBudgetBytes: 4_096,
      },
      autonomy: "ADVISORY",
      outputFormat: "synthetic-review-v1",
      confirmationRules: ["run_tests"],
      author: "AI Workspace synthetic fixtures",
      license: "Apache-2.0",
    },
    skills: [
      {
        id: "dependency-review",
        name: "Dependency review",
        description: "Inspects fictional dependency declarations.",
        version: "1.0.0",
        instructionSourceIds: ["dependency-review-rules"],
        requiredTools: ["read_file"],
        forbiddenTools: ["deploy"],
        inputs: ["dependency_manifest"],
        riskLevel: "LOW",
        destructiveActions: [],
        requiresConfirmation: [],
        outputFormat: "dependency-findings-v1",
        author: "AI Workspace synthetic fixtures",
        license: "Apache-2.0",
      },
      {
        id: "test-review",
        name: "Test review",
        description: "Runs a fictional reviewed test command.",
        version: "2.1.0-beta.1",
        instructionSourceIds: ["test-review-rules"],
        requiredTools: ["run_tests"],
        forbiddenTools: ["write_file"],
        inputs: ["test_command"],
        riskLevel: "MEDIUM",
        destructiveActions: ["run_tests"],
        requiresConfirmation: ["run_tests"],
        outputFormat: "test-findings-v1",
        author: "AI Workspace synthetic fixtures",
        license: "Apache-2.0",
      },
    ],
    effect: "DESCRIPTIVE_NOT_INSTALLED_SELECTED_ENFORCED_OR_EXECUTED",
  };
}
